<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0                              http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>se.fk.maven</groupId>
    <artifactId>fk-maven-quarkus-parent</artifactId>
    <version>1.12.0</version>
  </parent>
  <groupId>se.fk.rimfrost.framework.regel.oul</groupId>
  <artifactId>rimfrost-framework-regel-oul</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>Rimfrost Framework regel oul</name>

  <distributionManagement>
    <repository>
      <id>github--Forsakringskassan--repository</id>
      <url>https://maven.pkg.github.com/Forsakringskassan/repository</url>
    </repository>
  </distributionManagement>

  <properties>
    <quarkus.build.skip>true</quarkus.build.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-flyway</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-validator</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit-mockito</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.immutables</groupId>
      <artifactId>value</artifactId>
      <version>2.12.2</version>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>2.6</version>
    </dependency>
    <dependency>
      <groupId>se.fk.github.logging</groupId>
      <artifactId>fk-logging</artifactId>
      <version>0.3.0</version>
    </dependency>
    <dependency>
      <groupId>se.fk.rimfrost.framework.oul</groupId>
      <artifactId>rimfrost-framework-oul</artifactId>
      <version>1.1.1</version>
    </dependency>
    <dependency>
      <groupId>se.fk.rimfrost.framework.regel</groupId>
      <artifactId>rimfrost-framework-regel</artifactId>
      <version>1.4.2</version>
    </dependency>
    <dependency>
      <groupId>se.fk.rimfrost.framework.regel</groupId>
      <artifactId>rimfrost-framework-regel</artifactId>
      <version>1.4.2</version>
      <classifier>tests</classifier>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wiremock</groupId>
      <artifactId>wiremock</artifactId>
      <version>3.13.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.smallrye.reactive</groupId>
      <artifactId>smallrye-reactive-messaging-in-memory</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>se.fk.rimfrost.framework.oul</groupId>
      <artifactId>rimfrost-framework-oul-adapter</artifactId>
      <version>1.1.4</version>
    </dependency>
    <dependency>
      <groupId>se.fk.rimfrost.framework.referensdata</groupId>
      <artifactId>rimfrost-framework-referensdata-interface</artifactId>
      <version>0.0.1</version>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <version>4.3.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>central</id>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository>
      <id>github--Forsakringskassan--repository</id>
      <url>https://maven.pkg.github.com/Forsakringskassan/repository</url>
    </repository>
  </repositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.15.0</version>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
          <annotationProcessorPaths>
            <path>
              <groupId>org.immutables</groupId>
              <artifactId>value-processor</artifactId>
              <version>2.12.2</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>properties</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>**/Abstract*.java</exclude>
          </excludes>
          <argLine>@{argLine} -javaagent:${org.mockito:mockito-core:jar}</argLine>
        </configuration>
      </plugin>
      <plugin>
        <groupId>io.smallrye</groupId>
        <artifactId>jandex-maven-plugin</artifactId>
        <version>3.2.7</version>
        <executions>
          <execution>
            <id>make-index</id>
            <goals>
              <goal>jandex</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.5.1</version>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
            <configuration>
              <includes>
                <include>**/base/</include>
                <include>**/helpers/</include>
              </includes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
